package deploy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/spinnaker/spinctl/internal/config"
	"github.com/spinnaker/spinctl/internal/model"
)

func TestExportConfigsCreatesSpinnakerYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	cfg.Timezone = "America/Los_Angeles"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "spinnaker.yml"))
	if err != nil {
		t.Fatalf("reading spinnaker.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "gate") {
		t.Error("spinnaker.yml should contain gate service")
	}
	if !strings.Contains(content, "redis") {
		t.Error("spinnaker.yml should contain redis")
	}
	if !strings.Contains(content, "America/Los_Angeles") {
		t.Error("spinnaker.yml should contain timezone")
	}
	if !strings.Contains(content, "autogenerated by spinctl") {
		t.Error("spinnaker.yml should contain header")
	}
}

func TestExportConfigsCreatesServiceYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true
	gate.Host = "0.0.0.0"
	gate.Port = 8084
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "gate.yml"))
	if err != nil {
		t.Fatalf("reading gate.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "spectator") {
		t.Error("gate.yml should contain spectator config")
	}
	if !strings.Contains(content, "server") {
		t.Error("gate.yml should contain server block")
	}
}

func TestExportConfigsClouddriverProviders(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	cd := cfg.Services[model.Clouddriver]
	cd.Enabled = true
	cfg.Services[model.Clouddriver] = cd
	cfg.Providers = map[string]config.ProviderConfig{
		"aws": {
			Enabled: true,
			Accounts: []config.ProviderAccount{
				{Name: "my-aws"},
			},
		},
		"kubernetes": {
			Enabled: false,
		},
	}
	cfg.Artifacts = map[string]any{
		"s3": map[string]any{"enabled": true},
	}

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "clouddriver.yml"))
	if err != nil {
		t.Fatalf("reading clouddriver.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "aws") {
		t.Error("clouddriver.yml should contain aws provider")
	}
	if !strings.Contains(content, "my-aws") {
		t.Error("clouddriver.yml should contain account name")
	}
	if !strings.Contains(content, "artifacts") {
		t.Error("clouddriver.yml should contain artifacts")
	}
}

func TestExportConfigsFront50Storage(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	f50 := cfg.Services[model.Front50]
	f50.Enabled = true
	cfg.Services[model.Front50] = f50
	cfg.PersistentStorage = map[string]any{
		"persistentStoreType": "s3",
		"s3": map[string]any{
			"bucket": "my-bucket",
			"region": "us-west-2",
		},
	}

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "front50.yml"))
	if err != nil {
		t.Fatalf("reading front50.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "s3") {
		t.Error("front50.yml should contain s3 storage config")
	}
	if !strings.Contains(content, "my-bucket") {
		t.Error("front50.yml should contain bucket name")
	}
}

func TestExportConfigsLocalYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true

	// Add settings via yaml.Node.
	settingsYaml := `server:
  ssl:
    enabled: true
    keyStore: /path/to/keystore.jks
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: test123`
	var node yaml.Node
	yaml.Unmarshal([]byte(settingsYaml), &node)
	if node.Kind == yaml.DocumentNode && len(node.Content) > 0 {
		gate.Settings = *node.Content[0]
	}
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "gate-local.yml"))
	if err != nil {
		t.Fatalf("reading gate-local.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "ssl") {
		t.Error("gate-local.yml should contain ssl settings")
	}
	if !strings.Contains(content, "oauth2") {
		t.Error("gate-local.yml should contain oauth2 settings")
	}
	if !strings.Contains(content, "test123") {
		t.Error("gate-local.yml should contain client-id")
	}
}

func TestExportConfigsNoLocalYmlWhenNoSettings(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	orca := cfg.Services[model.Orca]
	orca.Enabled = true
	cfg.Services[model.Orca] = orca

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	localPath := filepath.Join(dir, "orca-local.yml")
	if _, err := os.Stat(localPath); err == nil {
		t.Error("orca-local.yml should not exist when no settings")
	}
}

func TestExportConfigsDisabledServiceSkipped(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	// All services disabled by default.

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	// Only spinnaker.yml should exist.
	if _, err := os.Stat(filepath.Join(dir, "spinnaker.yml")); err != nil {
		t.Error("spinnaker.yml should exist")
	}
	if _, err := os.Stat(filepath.Join(dir, "gate.yml")); err == nil {
		t.Error("gate.yml should not exist when disabled")
	}
}

func TestExportConfigsEcho(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	echo := cfg.Services[model.Echo]
	echo.Enabled = true
	cfg.Services[model.Echo] = echo
	cfg.Notifications = map[string]any{"slack": map[string]any{"enabled": true}}
	cfg.Pubsub = map[string]any{"google": map[string]any{"enabled": false}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "echo.yml"))
	content := string(data)
	if !strings.Contains(content, "notifications") {
		t.Error("echo.yml should contain notifications")
	}
	if !strings.Contains(content, "pubsub") {
		t.Error("echo.yml should contain pubsub")
	}
}

func TestExportConfigsIgor(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	igor := cfg.Services[model.Igor]
	igor.Enabled = true
	cfg.Services[model.Igor] = igor
	cfg.CI = map[string]any{"jenkins": map[string]any{"enabled": true}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "igor.yml"))
	if !strings.Contains(string(data), "jenkins") {
		t.Error("igor.yml should contain jenkins CI config")
	}
}

func TestExportConfigsFiat(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	fiat := cfg.Services[model.Fiat]
	fiat.Enabled = true
	cfg.Services[model.Fiat] = fiat
	cfg.Security.Authz.Enabled = true

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "fiat.yml"))
	if !strings.Contains(string(data), "fiat") {
		t.Error("fiat.yml should contain fiat enabled config")
	}
}

func TestExportConfigsKayenta(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	k := cfg.Services[model.Kayenta]
	k.Enabled = true
	cfg.Services[model.Kayenta] = k
	cfg.Canary = map[string]any{"enabled": true}
	cfg.MetricStores = map[string]any{"prometheus": map[string]any{"enabled": true}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "kayenta.yml"))
	content := string(data)
	if !strings.Contains(content, "canary") {
		t.Error("kayenta.yml should contain canary config")
	}
	if !strings.Contains(content, "metricStores") {
		t.Error("kayenta.yml should contain metric stores")
	}
}
