package deploy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/spinnaker/spinctl/internal/config"
	"github.com/spinnaker/spinctl/internal/model"
)

func TestExportConfigsCreatesSpinnakerYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	cfg.Timezone = "America/Los_Angeles"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "spinnaker.yml"))
	if err != nil {
		t.Fatalf("reading spinnaker.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "gate") {
		t.Error("spinnaker.yml should contain gate service")
	}
	if !strings.Contains(content, "redis") {
		t.Error("spinnaker.yml should contain redis")
	}
	if !strings.Contains(content, "America/Los_Angeles") {
		t.Error("spinnaker.yml should contain timezone")
	}
	if !strings.Contains(content, "autogenerated by spinctl") {
		t.Error("spinnaker.yml should contain header")
	}
}

func TestExportConfigsCreatesServiceYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true
	gate.Host = "0.0.0.0"
	gate.Port = 8084
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "gate.yml"))
	if err != nil {
		t.Fatalf("reading gate.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "spectator") {
		t.Error("gate.yml should contain spectator config")
	}
	if !strings.Contains(content, "server") {
		t.Error("gate.yml should contain server block")
	}
}

func TestExportConfigsClouddriverProviders(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	cd := cfg.Services[model.Clouddriver]
	cd.Enabled = true
	cfg.Services[model.Clouddriver] = cd
	cfg.Providers = map[string]config.ProviderConfig{
		"aws": {
			Enabled: true,
			Accounts: []config.ProviderAccount{
				{Name: "my-aws"},
			},
		},
		"kubernetes": {
			Enabled: false,
		},
	}
	cfg.Artifacts = map[string]any{
		"s3": map[string]any{"enabled": true},
	}

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "clouddriver.yml"))
	if err != nil {
		t.Fatalf("reading clouddriver.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "aws") {
		t.Error("clouddriver.yml should contain aws provider")
	}
	if !strings.Contains(content, "my-aws") {
		t.Error("clouddriver.yml should contain account name")
	}
	if !strings.Contains(content, "artifacts") {
		t.Error("clouddriver.yml should contain artifacts")
	}
}

func TestExportConfigsFront50Storage(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	f50 := cfg.Services[model.Front50]
	f50.Enabled = true
	cfg.Services[model.Front50] = f50
	cfg.PersistentStorage = map[string]any{
		"persistentStoreType": "s3",
		"s3": map[string]any{
			"bucket": "my-bucket",
			"region": "us-west-2",
		},
	}

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "front50.yml"))
	if err != nil {
		t.Fatalf("reading front50.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "s3") {
		t.Error("front50.yml should contain s3 storage config")
	}
	if !strings.Contains(content, "my-bucket") {
		t.Error("front50.yml should contain bucket name")
	}
}

func TestExportConfigsLocalYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	gate := cfg.Services[model.Gate]
	gate.Enabled = true

	// Add settings via yaml.Node.
	settingsYaml := `server:
  ssl:
    enabled: true
    keyStore: /path/to/keystore.jks
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: test123`
	var node yaml.Node
	yaml.Unmarshal([]byte(settingsYaml), &node)
	if node.Kind == yaml.DocumentNode && len(node.Content) > 0 {
		gate.Settings = *node.Content[0]
	}
	cfg.Services[model.Gate] = gate

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "gate-local.yml"))
	if err != nil {
		t.Fatalf("reading gate-local.yml: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "ssl") {
		t.Error("gate-local.yml should contain ssl settings")
	}
	if !strings.Contains(content, "oauth2") {
		t.Error("gate-local.yml should contain oauth2 settings")
	}
	if !strings.Contains(content, "test123") {
		t.Error("gate-local.yml should contain client-id")
	}
}

func TestExportConfigsNoLocalYmlWhenNoSettings(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	orca := cfg.Services[model.Orca]
	orca.Enabled = true
	cfg.Services[model.Orca] = orca

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	localPath := filepath.Join(dir, "orca-local.yml")
	if _, err := os.Stat(localPath); err == nil {
		t.Error("orca-local.yml should not exist when no settings")
	}
}

func TestExportConfigsDisabledServiceSkipped(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	// All services disabled by default.

	dir := t.TempDir()
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs: %v", err)
	}

	// Only spinnaker.yml should exist.
	if _, err := os.Stat(filepath.Join(dir, "spinnaker.yml")); err != nil {
		t.Error("spinnaker.yml should exist")
	}
	if _, err := os.Stat(filepath.Join(dir, "gate.yml")); err == nil {
		t.Error("gate.yml should not exist when disabled")
	}
}

func TestExportConfigsEcho(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	echo := cfg.Services[model.Echo]
	echo.Enabled = true
	cfg.Services[model.Echo] = echo
	cfg.Notifications = map[string]any{"slack": map[string]any{"enabled": true}}
	cfg.Pubsub = map[string]any{"google": map[string]any{"enabled": false}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "echo.yml"))
	content := string(data)
	if !strings.Contains(content, "notifications") {
		t.Error("echo.yml should contain notifications")
	}
	if !strings.Contains(content, "pubsub") {
		t.Error("echo.yml should contain pubsub")
	}
}

func TestExportConfigsIgor(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	igor := cfg.Services[model.Igor]
	igor.Enabled = true
	cfg.Services[model.Igor] = igor
	cfg.CI = map[string]any{"jenkins": map[string]any{"enabled": true}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "igor.yml"))
	if !strings.Contains(string(data), "jenkins") {
		t.Error("igor.yml should contain jenkins CI config")
	}
}

func TestExportConfigsFiat(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	fiat := cfg.Services[model.Fiat]
	fiat.Enabled = true
	cfg.Services[model.Fiat] = fiat
	cfg.Security.Authz.Enabled = true

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "fiat.yml"))
	if !strings.Contains(string(data), "fiat") {
		t.Error("fiat.yml should contain fiat enabled config")
	}
}

func TestExportConfigsKayenta(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	k := cfg.Services[model.Kayenta]
	k.Enabled = true
	cfg.Services[model.Kayenta] = k
	cfg.Canary = map[string]any{"enabled": true}
	cfg.MetricStores = map[string]any{"prometheus": map[string]any{"enabled": true}}

	dir := t.TempDir()
	ExportConfigs(cfg, dir)

	data, _ := os.ReadFile(filepath.Join(dir, "kayenta.yml"))
	content := string(data)
	if !strings.Contains(content, "canary") {
		t.Error("kayenta.yml should contain canary config")
	}
	if !strings.Contains(content, "metricStores") {
		t.Error("kayenta.yml should contain metric stores")
	}
}

// --- backupConfigDir tests ---

func TestBackupConfigDir(t *testing.T) {
	dir := t.TempDir()

	// Create some .yml files.
	os.WriteFile(filepath.Join(dir, "gate.yml"), []byte("gate config"), 0644)
	os.WriteFile(filepath.Join(dir, "orca.yml"), []byte("orca config"), 0644)
	os.WriteFile(filepath.Join(dir, "settings-local.js"), []byte("var x=1;"), 0644)
	// A .txt file should NOT be backed up.
	os.WriteFile(filepath.Join(dir, "readme.txt"), []byte("ignore me"), 0644)

	if err := backupConfigDir(dir); err != nil {
		t.Fatalf("backupConfigDir: %v", err)
	}

	// Find the backup directory.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("reading dir: %v", err)
	}
	var backupDirName string
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "backup.") {
			backupDirName = e.Name()
			break
		}
	}
	if backupDirName == "" {
		t.Fatal("expected a backup.* directory to be created")
	}

	backupPath := filepath.Join(dir, backupDirName)
	// Verify .yml and .js files were copied.
	for _, name := range []string{"gate.yml", "orca.yml", "settings-local.js"} {
		data, err := os.ReadFile(filepath.Join(backupPath, name))
		if err != nil {
			t.Errorf("expected %s in backup: %v", name, err)
			continue
		}
		if len(data) == 0 {
			t.Errorf("backup of %s should not be empty", name)
		}
	}
	// Verify .txt was NOT copied.
	if _, err := os.Stat(filepath.Join(backupPath, "readme.txt")); err == nil {
		t.Error("readme.txt should not be backed up")
	}
}

func TestBackupConfigDirEmpty(t *testing.T) {
	dir := t.TempDir()
	// Empty dir (no .yml or .js files).

	if err := backupConfigDir(dir); err != nil {
		t.Fatalf("backupConfigDir on empty dir: %v", err)
	}

	// No backup directory should be created.
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if e.IsDir() && strings.HasPrefix(e.Name(), "backup.") {
			t.Error("no backup dir should be created for empty directory")
		}
	}
}

func TestBackupConfigDirNoExist(t *testing.T) {
	nonexistent := filepath.Join(t.TempDir(), "does-not-exist")
	if err := backupConfigDir(nonexistent); err != nil {
		t.Fatalf("backupConfigDir on nonexistent dir should not error: %v", err)
	}
}

// --- findSettingsValue tests ---

func TestFindSettingsValue(t *testing.T) {
	var node yaml.Node
	yaml.Unmarshal([]byte("ssl:\n  enabled: true\n  certFile: /path/cert"), &node)
	if node.Kind == yaml.DocumentNode {
		node = *node.Content[0]
	}

	val := findSettingsValue(&node, "ssl", "enabled")
	if val != "true" {
		t.Errorf("expected 'true', got %q", val)
	}

	val = findSettingsValue(&node, "ssl", "certFile")
	if val != "/path/cert" {
		t.Errorf("expected '/path/cert', got %q", val)
	}
}

func TestFindSettingsValueMissing(t *testing.T) {
	var node yaml.Node
	yaml.Unmarshal([]byte("ssl:\n  enabled: true"), &node)
	if node.Kind == yaml.DocumentNode {
		node = *node.Content[0]
	}

	val := findSettingsValue(&node, "ssl", "missing")
	if val != "" {
		t.Errorf("expected empty string, got %q", val)
	}

	val = findSettingsValue(&node, "nonexistent")
	if val != "" {
		t.Errorf("expected empty string for missing top-level key, got %q", val)
	}
}

func TestFindSettingsValueNonMapping(t *testing.T) {
	var node yaml.Node
	yaml.Unmarshal([]byte("hello"), &node)
	if node.Kind == yaml.DocumentNode {
		node = *node.Content[0]
	}

	val := findSettingsValue(&node, "hello")
	if val != "" {
		t.Errorf("expected empty string for scalar node, got %q", val)
	}
}

func TestFindSettingsValueDocumentNode(t *testing.T) {
	// Pass a DocumentNode directly to exercise the unwrap path.
	var node yaml.Node
	yaml.Unmarshal([]byte("ssl:\n  enabled: true"), &node)

	val := findSettingsValue(&node, "ssl", "enabled")
	if val != "true" {
		t.Errorf("expected 'true' via document node, got %q", val)
	}
}

// --- writeDeckSettings tests ---

func TestWriteDeckSettingsDisabled(t *testing.T) {
	cfg := config.NewDefault()
	// Deck disabled by default.
	dir := t.TempDir()
	if err := writeDeckSettings(cfg, dir); err != nil {
		t.Fatalf("writeDeckSettings with disabled deck: %v", err)
	}
	// Nothing should be written.
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Error("no files should be written when deck is disabled")
	}
}

func TestWriteDeckSettingsNoProfileFiles(t *testing.T) {
	cfg := config.NewDefault()
	deck := cfg.Services[model.Deck]
	deck.Enabled = true
	cfg.Services[model.Deck] = deck
	// No ProfileFiles set.

	dir := t.TempDir()
	// writeApacheConfig will fail because /etc/apache2 is not writable,
	// so this should return an error.
	err := writeDeckSettings(cfg, dir)
	if err == nil {
		// If running as root or apache dir exists, this might succeed.
		return
	}
	if !strings.Contains(err.Error(), "Apache") {
		t.Errorf("expected Apache-related error, got: %v", err)
	}
}

// --- buildRoscoYml tests ---

func TestBuildRoscoYml(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Providers = map[string]config.ProviderConfig{
		"aws": {
			Enabled: true,
			Extra: map[string]any{
				"bakeryDefaults": map[string]any{
					"templateFile": "aws-ebs-shared.json",
				},
			},
		},
	}

	content := serviceBoilerplate(model.Rosco)
	buildRoscoYml(cfg, content)

	rosco, ok := content["rosco"].(map[string]any)
	if !ok {
		t.Fatal("expected rosco key in content")
	}
	aws, ok := rosco["aws"].(map[string]any)
	if !ok {
		t.Fatal("expected aws key in rosco")
	}
	if aws["enabled"] != true {
		t.Error("expected aws enabled=true in rosco")
	}
	if aws["bakeryDefaults"] == nil {
		t.Error("expected bakeryDefaults in rosco.aws")
	}
}

func TestBuildRoscoYmlNoProviders(t *testing.T) {
	cfg := config.NewDefault()
	content := serviceBoilerplate(model.Rosco)
	buildRoscoYml(cfg, content)

	if _, ok := content["rosco"]; ok {
		t.Error("rosco key should not exist when no providers have bakeryDefaults")
	}
}

// --- buildOrcaYml tests ---

func TestBuildOrcaYmlNoWebhook(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Webhook = nil

	content := serviceBoilerplate(model.Orca)
	buildOrcaYml(cfg, content)

	if _, ok := content["webhook"]; ok {
		t.Error("orca should not contain webhook key when Webhook is nil")
	}
}

func TestBuildOrcaYmlWithWebhook(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Webhook = map[string]any{"trust": map[string]any{"enabled": true}}

	content := serviceBoilerplate(model.Orca)
	buildOrcaYml(cfg, content)

	if _, ok := content["webhook"]; !ok {
		t.Error("orca should contain webhook key")
	}
}

// --- ExportConfigs with ProfileFiles ---

func TestExportConfigsWithProfileFiles(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Version = "2025.3.2"
	cfg.ProfileFiles = map[string]string{
		"custom-config.js": "var custom = true;",
	}

	dir := t.TempDir()
	// /opt/deck/html is not writable in tests, so this should fall back to configDir.
	if err := ExportConfigs(cfg, dir); err != nil {
		t.Fatalf("ExportConfigs with profile files: %v", err)
	}

	// Check fallback path: the file should be in configDir.
	data, err := os.ReadFile(filepath.Join(dir, "custom-config.js"))
	if err != nil {
		t.Fatalf("expected custom-config.js to be written to config dir: %v", err)
	}
	if string(data) != "var custom = true;" {
		t.Errorf("unexpected content: %s", string(data))
	}
}

// --- buildEchoYml with pubsub ---

func TestBuildEchoYmlWithPubsub(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Pubsub = map[string]any{
		"google": map[string]any{
			"enabled":       true,
			"subscriptions": []any{"sub1"},
		},
	}

	content := serviceBoilerplate(model.Echo)
	buildEchoYml(cfg, content)

	pubsub, ok := content["pubsub"].(map[string]any)
	if !ok {
		t.Fatal("expected pubsub key in echo content")
	}
	google, ok := pubsub["google"].(map[string]any)
	if !ok {
		t.Fatal("expected google key in pubsub")
	}
	if google["enabled"] != true {
		t.Error("expected google pubsub enabled=true")
	}
}

func TestBuildEchoYmlWithStats(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Stats = map[string]any{"enabled": true}

	content := serviceBoilerplate(model.Echo)
	buildEchoYml(cfg, content)

	if _, ok := content["stats"]; !ok {
		t.Error("expected stats key in echo content")
	}
}

// --- buildIgorYml with repository ---

func TestBuildIgorYmlWithRepository(t *testing.T) {
	cfg := config.NewDefault()
	cfg.Repository = map[string]any{
		"artifactory": map[string]any{
			"enabled":  true,
			"searches": []any{"libs-release"},
		},
	}

	content := serviceBoilerplate(model.Igor)
	buildIgorYml(cfg, content)

	repo, ok := content["repository"].(map[string]any)
	if !ok {
		t.Fatal("expected repository key in igor content")
	}
	if repo["artifactory"] == nil {
		t.Error("expected artifactory key in repository")
	}
}

// --- buildFront50Yml merges spinnaker extensibility ---

func TestBuildFront50YmlMergesSpinnaker(t *testing.T) {
	cfg := config.NewDefault()
	cfg.PersistentStorage = map[string]any{
		"persistentStoreType": "s3",
	}

	content := serviceBoilerplate(model.Front50)
	buildFront50Yml(cfg, content)

	spinCfg, ok := content["spinnaker"].(map[string]any)
	if !ok {
		t.Fatal("expected spinnaker key in front50 content")
	}
	// Should have the extensibility from boilerplate.
	if _, ok := spinCfg["extensibility"]; !ok {
		t.Error("spinnaker.extensibility should be preserved from boilerplate")
	}
	// Should also have the storage type.
	if spinCfg["persistentStoreType"] != "s3" {
		t.Error("spinnaker.persistentStoreType should be s3")
	}
}

// --- writeApacheConfig error path ---

func TestWriteApacheConfigErrorPath(t *testing.T) {
	svc := config.ServiceConfig{
		Host: "0.0.0.0",
		Port: 9000,
	}
	// Should fail because /etc/apache2 is not writable in tests.
	err := writeApacheConfig(svc)
	if err == nil {
		// If running as root, this could succeed.
		return
	}
	// Just verify it doesn't panic and returns an error.
}

func TestWriteApacheConfigDefaults(t *testing.T) {
	svc := config.ServiceConfig{
		Host: "",
		Port: 0,
	}
	// Tests the default host/port paths. Will fail at file write.
	err := writeApacheConfig(svc)
	if err == nil {
		return
	}
	// Ensure defaults were applied (error is from file write, not from logic).
}

func TestWriteApacheConfigWithSSL(t *testing.T) {
	var settingsNode yaml.Node
	yaml.Unmarshal([]byte("ssl:\n  enabled: true\n  certFile: /etc/ssl/cert.pem\n  keyFile: /etc/ssl/key.pem"), &settingsNode)
	if settingsNode.Kind == yaml.DocumentNode {
		settingsNode = *settingsNode.Content[0]
	}

	svc := config.ServiceConfig{
		Host:     "0.0.0.0",
		Port:     9000,
		Settings: settingsNode,
	}
	// Will fail at file write, but exercises SSL code paths.
	_ = writeApacheConfig(svc)
}
