package deploy

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/spinnaker/spinctl/internal/config"
	"github.com/spinnaker/spinctl/internal/model"
)

const configHeader = "## WARNING\n## This file was autogenerated by spinctl, and _will_ be overwritten.\n## Any edits you make here _will_ be lost.\n\n"

// ExportConfigs writes all Spinnaker config files to the given directory.
// It backs up existing config files before overwriting.
func ExportConfigs(cfg *config.SpinctlConfig, configDir string) error {
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	// Backup existing config files before overwriting.
	if err := backupConfigDir(configDir); err != nil {
		return fmt.Errorf("backing up config: %w", err)
	}

	if err := writeSpinnakerYml(cfg, configDir); err != nil {
		return fmt.Errorf("writing spinnaker.yml: %w", err)
	}

	for name, svc := range cfg.Services {
		if !svc.Enabled {
			continue
		}
		// Deck config goes to Apache, not /opt/spinnaker/config/.
		if name == model.Deck {
			continue
		}
		if err := writeServiceYml(cfg, name, svc, configDir); err != nil {
			return fmt.Errorf("writing %s.yml: %w", name, err)
		}
		if err := writeServiceLocalYml(name, svc, configDir); err != nil {
			return fmt.Errorf("writing %s-local.yml: %w", name, err)
		}
	}

	// Write Deck settings and profile files to Apache document root.
	if err := writeDeckSettings(cfg, configDir); err != nil {
		return fmt.Errorf("writing deck settings: %w", err)
	}

	// Write raw profile files (settings-local.js, etc.) to Apache.
	deckDir := "/opt/deck/html"
	for filename, content := range cfg.ProfileFiles {
		path := filepath.Join(deckDir, filename)
		_ = os.MkdirAll(deckDir, 0755)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			// Fall back to config dir if deck dir is not writable.
			path = filepath.Join(configDir, filename)
			if err := os.WriteFile(path, []byte(content), 0640); err != nil {
				return fmt.Errorf("writing %s: %w", filename, err)
			}
		}
	}

	return nil
}

// writeSpinnakerYml generates the global spinnaker.yml with service endpoints.
func writeSpinnakerYml(cfg *config.SpinctlConfig, configDir string) error {
	services := make(map[string]any)

	for name, svc := range cfg.Services {
		protocol := "http"
		baseUrl := fmt.Sprintf("%s://%s:%d", protocol, svc.Host, svc.Port)

		entry := map[string]any{
			"host":    svc.Host,
			"port":    svc.Port,
			"baseUrl": baseUrl,
			"enabled": svc.Enabled,
		}
		services[name.String()] = entry
	}

	// Add redis as a service entry.
	services["redis"] = map[string]any{
		"host":    "localhost",
		"port":    6379,
		"baseUrl": "redis://localhost:6379",
		"enabled": true,
	}

	// Add monitoring daemon (disabled by default).
	services["monitoringDaemon"] = map[string]any{
		"host":    "localhost",
		"port":    8008,
		"baseUrl": "http://localhost:8008",
		"enabled": false,
	}

	content := map[string]any{
		"services": services,
	}

	if cfg.Timezone != "" {
		content["global.spinnaker.timezone"] = cfg.Timezone
	}

	return writeYamlFile(filepath.Join(configDir, "spinnaker.yml"), content)
}

// serviceBoilerplate returns the common spectator and extensibility config.
func serviceBoilerplate(name model.ServiceName) map[string]any {
	return map[string]any{
		"spectator": map[string]any{
			"applicationName": "${spring.application.name}",
			"webEndpoint": map[string]any{
				"enabled": false,
			},
		},
		"spinnaker": map[string]any{
			"extensibility": map[string]any{
				"plugins":               map[string]any{},
				"repositories":          map[string]any{},
				"plugins-root-path":     fmt.Sprintf("/opt/%s/plugins", name),
				"strict-plugin-loading": false,
			},
		},
	}
}

// serverBlock returns the standard server config with Spring property references.
func serverBlock(name model.ServiceName, svc config.ServiceConfig) map[string]any {
	return map[string]any{
		"port":    fmt.Sprintf("${services.%s.port:%d}", name, svc.Port),
		"address": fmt.Sprintf("${services.%s.host:%s}", name, svc.Host),
	}
}

// writeServiceYml generates the per-service <service>.yml base config.
func writeServiceYml(cfg *config.SpinctlConfig, name model.ServiceName, svc config.ServiceConfig, configDir string) error {
	content := serviceBoilerplate(name)
	content["server"] = serverBlock(name, svc)

	switch name {
	case model.Clouddriver:
		buildClouddriverYml(cfg, content)
	case model.Gate:
		buildGateYml(cfg, svc, content)
	case model.Front50:
		buildFront50Yml(cfg, content)
	case model.Echo:
		buildEchoYml(cfg, content)
	case model.Igor:
		buildIgorYml(cfg, content)
	case model.Fiat:
		buildFiatYml(cfg, content)
	case model.Kayenta:
		buildKayentaYml(cfg, content)
	case model.Orca:
		buildOrcaYml(cfg, content)
	case model.Rosco:
		buildRoscoYml(cfg, content)
	}

	return writeYamlFile(filepath.Join(configDir, name.ConfigFile()), content)
}

func buildClouddriverYml(cfg *config.SpinctlConfig, content map[string]any) {
	// All providers go into clouddriver.
	if cfg.Providers != nil {
		for provName, prov := range cfg.Providers {
			provMap := map[string]any{
				"enabled":  prov.Enabled,
				"accounts": prov.Accounts,
			}
			// Merge extra fields.
			for k, v := range prov.Extra {
				provMap[k] = v
			}
			content[provName] = provMap
		}
	}

	// Artifacts.
	if cfg.Artifacts != nil {
		content["artifacts"] = cfg.Artifacts
	}
}

func buildGateYml(cfg *config.SpinctlConfig, svc config.ServiceConfig, content map[string]any) {
	// Gate server block with SSL defaults.
	content["server"] = map[string]any{
		"ssl": map[string]any{
			"enabled":    false,
			"clientAuth": "WANT",
		},
		"port":    fmt.Sprintf("%d", svc.Port),
		"address": svc.Host,
	}

	content["security"] = map[string]any{
		"basic": map[string]any{"enabled": true},
		"user":  map[string]any{},
	}
}

func buildFront50Yml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.PersistentStorage != nil {
		spinCfg := make(map[string]any)
		for k, v := range cfg.PersistentStorage {
			spinCfg[k] = v
		}
		// Merge into the existing spinnaker key from boilerplate.
		if existing, ok := content["spinnaker"].(map[string]any); ok {
			for k, v := range spinCfg {
				existing[k] = v
			}
		} else {
			content["spinnaker"] = spinCfg
		}
	}
}

func buildEchoYml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.Notifications != nil {
		content["notifications"] = cfg.Notifications
	}
	if cfg.Stats != nil {
		content["stats"] = cfg.Stats
	}
	if cfg.Pubsub != nil {
		content["pubsub"] = cfg.Pubsub
	}
}

func buildIgorYml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.CI != nil {
		// CI integrations go directly into igor.
		for k, v := range cfg.CI {
			content[k] = v
		}
	}
	if cfg.Repository != nil {
		content["repository"] = cfg.Repository
	}
}

func buildFiatYml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.Security.Authz.Enabled {
		content["fiat"] = map[string]any{"enabled": true}
	}
}

func buildKayentaYml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.Canary != nil {
		content["canary"] = cfg.Canary
	}
	if cfg.MetricStores != nil {
		content["metricStores"] = cfg.MetricStores
	}
}

func buildOrcaYml(cfg *config.SpinctlConfig, content map[string]any) {
	if cfg.Webhook != nil {
		content["webhook"] = cfg.Webhook
	}
}

// writeDeckSettings writes Deck's settings-local.js to the Apache document root
// and generates the Apache vhost configuration.
func writeDeckSettings(cfg *config.SpinctlConfig, configDir string) error {
	deckSvc, ok := cfg.Services[model.Deck]
	if !ok || !deckSvc.Enabled {
		return nil
	}

	deckDir := "/opt/deck/html"
	_ = os.MkdirAll(deckDir, 0755)

	// Write settings-local.js from profile files if it exists.
	if js, ok := cfg.ProfileFiles["settings-local.js"]; ok {
		path := filepath.Join(deckDir, "settings-local.js")
		if err := os.WriteFile(path, []byte(js), 0644); err != nil {
			// Fall back to config dir.
			_ = os.WriteFile(filepath.Join(configDir, "settings-local.js"), []byte(js), 0640)
		}
	}

	// Generate Apache vhost config.
	if err := writeApacheConfig(deckSvc); err != nil {
		return fmt.Errorf("writing Apache config: %w", err)
	}

	return nil
}

// writeApacheConfig generates the Apache virtual host configuration for Deck.
func writeApacheConfig(svc config.ServiceConfig) error {
	host := svc.Host
	if host == "" {
		host = "0.0.0.0"
	}
	port := svc.Port
	if port == 0 {
		port = 9000
	}

	// Check for SSL settings in the service's Settings yaml.Node.
	sslEnabled := false
	sslCertFile := ""
	sslKeyFile := ""
	if svc.Settings.Kind != 0 {
		if val := findSettingsValue(&svc.Settings, "ssl", "enabled"); val == "true" {
			sslEnabled = true
		}
		if val := findSettingsValue(&svc.Settings, "ssl", "certFile"); val != "" {
			sslCertFile = val
		}
		if val := findSettingsValue(&svc.Settings, "ssl", "keyFile"); val != "" {
			sslKeyFile = val
		}
	}

	var b strings.Builder
	b.WriteString(configHeader)
	b.WriteString(fmt.Sprintf("<VirtualHost %s:%d>\n", host, port))

	if sslEnabled {
		b.WriteString("  <IfModule ssl_module>\n")
		b.WriteString("    SSLEngine on\n")
		b.WriteString(fmt.Sprintf("    SSLCertificateFile \"%s\"\n", sslCertFile))
		b.WriteString(fmt.Sprintf("    SSLCertificateKeyFile \"%s\"\n", sslKeyFile))
		b.WriteString("  </IfModule>\n")
	}

	b.WriteString("  DocumentRoot /opt/deck/html\n")
	b.WriteString("\n")
	b.WriteString("  <Directory \"/opt/deck/html/\">\n")
	b.WriteString("     Require all granted\n")
	b.WriteString("  </Directory>\n")
	b.WriteString("</VirtualHost>\n")

	apacheConf := "/etc/apache2/sites-enabled/spinnaker.conf"
	return os.WriteFile(apacheConf, []byte(b.String()), 0644)
}

// findSettingsValue walks a yaml.Node to find a nested value by keys.
func findSettingsValue(node *yaml.Node, keys ...string) string {
	current := node
	if current.Kind == yaml.DocumentNode && len(current.Content) > 0 {
		current = current.Content[0]
	}
	for _, key := range keys {
		if current.Kind != yaml.MappingNode {
			return ""
		}
		found := false
		for i := 0; i+1 < len(current.Content); i += 2 {
			if current.Content[i].Value == key {
				current = current.Content[i+1]
				found = true
				break
			}
		}
		if !found {
			return ""
		}
	}
	if current.Kind == yaml.ScalarNode {
		return current.Value
	}
	return ""
}

func buildRoscoYml(cfg *config.SpinctlConfig, content map[string]any) {
	// Rosco gets bakery defaults from providers.
	if cfg.Providers != nil {
		for provName, prov := range cfg.Providers {
			if bakery, ok := prov.Extra["bakeryDefaults"]; ok {
				if content["rosco"] == nil {
					content["rosco"] = map[string]any{}
				}
				rosco := content["rosco"].(map[string]any)
				rosco[provName] = map[string]any{
					"enabled":         prov.Enabled,
					"bakeryDefaults":  bakery,
				}
			}
		}
	}
}

// writeServiceLocalYml generates the per-service <service>-local.yml override file.
func writeServiceLocalYml(name model.ServiceName, svc config.ServiceConfig, configDir string) error {
	localFile := filepath.Join(configDir, name.String()+"-local.yml")

	if svc.Settings.Kind == 0 || len(svc.Settings.Content) == 0 {
		// No settings — remove stale local file if it exists.
		_ = os.Remove(localFile)
		return nil
	}

	// Marshal the yaml.Node directly to preserve types and structure.
	data, err := yaml.Marshal(&svc.Settings)
	if err != nil {
		return fmt.Errorf("marshaling %s-local settings: %w", name, err)
	}

	return writeRawFile(localFile, data)
}

func writeYamlFile(path string, content any) error {
	data, err := yaml.Marshal(content)
	if err != nil {
		return err
	}
	return writeRawFile(path, data)
}

func writeRawFile(path string, data []byte) error {
	out := []byte(configHeader)
	out = append(out, data...)
	return os.WriteFile(path, out, 0640)
}

// backupConfigDir copies all .yml and .js files from configDir to a timestamped
// backup directory. Only runs if configDir already contains files.
func backupConfigDir(configDir string) error {
	// Check if there are any config files to back up.
	entries, err := os.ReadDir(configDir)
	if err != nil {
		return nil // Directory doesn't exist yet, nothing to back up.
	}

	hasFiles := false
	for _, e := range entries {
		if !e.IsDir() && (filepath.Ext(e.Name()) == ".yml" || filepath.Ext(e.Name()) == ".js") {
			hasFiles = true
			break
		}
	}
	if !hasFiles {
		return nil
	}

	timestamp := time.Now().Format("20060102-150405")
	backupDir := filepath.Join(configDir, fmt.Sprintf("backup.%s", timestamp))
	if err := os.MkdirAll(backupDir, 0755); err != nil {
		return fmt.Errorf("creating backup dir: %w", err)
	}

	err = filepath.WalkDir(configDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// Skip the backup directory itself and subdirectories.
		if d.IsDir() {
			if path != configDir {
				return fs.SkipDir
			}
			return nil
		}
		// Only back up .yml and .js files.
		ext := filepath.Ext(d.Name())
		if ext != ".yml" && ext != ".js" {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(filepath.Join(backupDir, d.Name()), data, 0640)
	})

	return err
}
